//ERROR
export const MOSTRAR_ERROR = "MOSTRAR_ERROR";
export const OCULTAR_ERROR = "OCULTAR_ERROR";

//AUTH
export const REGISTRO_EXITOSO =  "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO ="LOGIN_EXITOSO";
export const LOGIN_ERROR ="LOGIN_ERROR";
export const CERRAR_SESION ="CERRAR_SESION";
export const REGISTRO_EXITOSO_GOOGLE ="REGISTRO_EXITOSO_GOOGLE";

