//ERROR
export const MOSTRAR_ERROR = "MOSTRAR_ERROR";
export const OCULTAR_ERROR = "OCULTAR_ERROR";

//AUTH
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const REGISTRO_EXITOSO_GOOGLE = "REGISTRO_EXITOSO_GOOGLE";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USUARIOS = "GET_USUARIOS";

export const GET_PREGUNTAS_MATH = "GET_PREGUNTAS_MATH";
export const GET_PREGUNTAS_SOCIELES = "GET_PREGUNTAS_SOCIELES";
export const GET_PREGUNTAS_CIENCIAS = "GET_PREGUNTAS_CIENCIAS";
export const GET_PREGUNTAS_LENGUAJE = "GET_PREGUNTAS_LENGUAJE";

export const CARGAR_AMIGOS  = "CARGAR_AMIGOS"
export const CARGAR_AMIGOS_ERR = "CARGAR_AMIGOS_ERR";

export const GET_SOLICITUDES = "GET_SOLICITUDES";
export const DELTE_SOLICITUD = "DELTE_SOLICITUD";
